meta-ti-bsp: mesa-pvr: direct assignment to RRECOMMENDS temporarily
Issue: LINUXEXEC-26271

Normally the config file should set
PREFERRED_PROVIDER_virtual/gpudriver = " ti-img-rogue-driver",

But this causes building issue with below, direct assignment to "RRECOMMENDS"
with "ti-img-rogue-driver" works fine. So as a workaround to add here.

ERROR: Nothing RPROVIDES 'ti-img-rogue-driver' (but recipes-graphics/mesa/mesa-pvr_22.3.5.bb RDEPENDS on or otherwise requires it)
ti-img-rogue-driver was skipped: We shouldn't have multilib variants for ti-img-rogue-driver
ti-img-rogue-driver was skipped: incompatible with machine ti-j72xx (not in COMPATIBLE_MACHINE)
ti-img-rogue-driver was skipped: We shouldn't have multilib variants for ti-img-rogue-driver
ti-img-rogue-driver was skipped: PREFERRED_PROVIDER_virtual/lib32-gpudriver set to lib32-ti-img-rogue-driver, not ti-img-rogue-driver
NOTE: Runtime target 'ti-img-rogue-driver' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ti-img-rogue-driver']
ERROR: Required build target 'mesa-pvr' has no buildable providers.
Missing or unbuildable dependency chain was: ['mesa-pvr', 'ti-img-rogue-driver']

(LOCAL REV: NOT UPSTREAM) - WRLinux specific

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>